name: CI

on:
  pull_request:
    branches: [ main, dev ]

jobs:
  build-and-test:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v2

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_13.4.app
      
      - name: Xcode version
        run: /usr/bin/xcodebuild -version
      
      - name: Build and Test
        run: xcodebuild clean build test -project Robowars/Robowars.xcodeproj -scheme "CI" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk macosx -destination "platform=macOS" ONLY_ACTIVE_ARCH=YES